-- MySQL Script generated by MySQL Workbench
-- Mon Mar 10 21:43:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `Sigla` CHAR(10) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `SuperArea` CHAR(10) NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Area_Area_idx` (`SuperArea` ASC) VISIBLE,
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  CONSTRAINT `fk_Area_Area`
    FOREIGN KEY (`SuperArea`)
    REFERENCES `mydb`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `Sigla` CHAR(10) NOT NULL,
  `Nome` VARCHAR(100) CHARACTER SET 'armscii8' NOT NULL,
  `Horas` INT NOT NULL,
  `Custo` INT NOT NULL,
  `SuperArea` CHAR(10) NOT NULL,
  PRIMARY KEY (`Sigla`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  INDEX `fk_Curso_Area1_idx` (`SuperArea` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Area1`
    FOREIGN KEY (`SuperArea`)
    REFERENCES `mydb`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modulo` (
  `Sigla` CHAR(10) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Curso` CHAR(10) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Modulo_Curso1_idx` (`Curso` ASC) VISIBLE,
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  CONSTRAINT `fk_Modulo_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Topico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Topico` (
  `Modulo` CHAR(10) NOT NULL,
  `Sigla` CHAR(10) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Horas` INT NULL,
  PRIMARY KEY (`Nome`, `Sigla`),
  INDEX `fk_Topico_Modulo1_idx` (`Modulo` ASC) VISIBLE,
  CONSTRAINT `fk_Topico_Modulo1`
    FOREIGN KEY (`Modulo`)
    REFERENCES `mydb`.`Modulo` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Sobrenome` VARCHAR(100) NULL,
  `Sexo` CHAR(1) NOT NULL,
  `DataNasc` DATE NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `Data` DATETIME NOT NULL,
  `Pago` TINYINT NOT NULL,
  `Curso` CHAR(10) NOT NULL,
  `Aluno` CHAR(11) NOT NULL,
  INDEX `fk_Matricula_Curso1_idx` (`Curso` ASC) VISIBLE,
  PRIMARY KEY (`Curso`),
  INDEX `fk_Matricula_Aluno1_idx` (`Aluno` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno`)
    REFERENCES `mydb`.`Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `Nome` VARCHAR(100) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `Curso` CHAR(10) NOT NULL,
  PRIMARY KEY (`CPF`, `Curso`),
  INDEX `fk_Professor_Curso1_idx` (`Curso` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
