ALTER TABLE Pessoa ADD CONSTRAINT PK_Pessoa PRIMARY KEY (cpf);
ALTER TABLE Instituicao ADD CONSTRAINT PK_Instituicao PRIMARY KEY (cnpj);
ALTER TABLE Receptor ADD CONSTRAINT PK_Receptor PRIMARY KEY (cpf);

ALTER TABLE Doacao ADD CONSTRAINT PK_Doacao PRIMARY KEY (id);
ALTER TABLE Item ADD CONSTRAINT PK_Item PRIMARY KEY (id);
ALTER TABLE Item_da_Doacao ADD CONSTRAINT PK_Item_da_Doacao PRIMARY KEY (Doacao_id, Item_id);
ALTER TABLE Estoque ADD CONSTRAINT PK_Estoque PRIMARY KEY (numero_registro, Item_id);
ALTER TABLE Venda ADD CONSTRAINT PK_Venda PRIMARY KEY (id);
ALTER TABLE Funcionario ADD CONSTRAINT PK_Funcionario PRIMARY KEY (cpf);
ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente PRIMARY KEY (cpf);
ALTER TABLE Gerencia ADD CONSTRAINT PK_Gerencia PRIMARY KEY (Funcionario_cpf, Doacao_id);

ALTER TABLE Doacao ADD CONSTRAINT FK_Doacao_Instituicao FOREIGN KEY (Instituicao_cnpj) REFERENCES Instituicao (cnpj) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE Doacao ADD CONSTRAINT FK_Doacao_Pessoa FOREIGN KEY (Pessoa_cpf) REFERENCES Pessoa (cpf) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE Doacao ADD CONSTRAINT FK_Doacao_Receptor FOREIGN KEY (Receptor_cpf) REFERENCES Receptor (cpf) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Item_da_Doacao ADD CONSTRAINT FK_Item_da_Doacao_Doacao FOREIGN KEY (Doacao_id) REFERENCES Doacao (id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE Item_da_Doacao ADD CONSTRAINT FK_Item_da_Doacao_Item FOREIGN KEY (Item_id) REFERENCES Item (id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Estoque ADD CONSTRAINT FK_Estoque_Item FOREIGN KEY (Item_id) REFERENCES Item (id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Funcionario ADD CONSTRAINT FK_Funcionario_Funcionario FOREIGN KEY (gestor_cpf) REFERENCES Funcionario (cpf) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Venda ADD CONSTRAINT FK_Venda_Estoque FOREIGN KEY (Estoque_numero_registro, Estoque_Item_id) REFERENCES Estoque (numero_registro, Item_id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE Venda ADD CONSTRAINT FK_Venda_Funcionario FOREIGN KEY (Funcionario_cpf) REFERENCES Funcionario (cpf) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE Venda ADD CONSTRAINT FK_Venda_Cliente FOREIGN KEY (Cliente_cpf) REFERENCES Cliente (cpf) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Gerencia ADD CONSTRAINT FK_Gerencia_Funcionario FOREIGN KEY (Funcionario_cpf) REFERENCES Funcionario (cpf) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE Gerencia ADD CONSTRAINT FK_Gerencia_Doacao FOREIGN KEY (Doacao_id) REFERENCES Doacao (id) ON DELETE RESTRICT ON UPDATE CASCADE;